#https://github.com/sproogen/modern-resume-theme
# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: José Giraldo Ruiz
title: Software engineering
email: dragojola@gmail.com
website: josgirrui.github.io/josgirrui/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  josgirrui
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: josgiraldoruiz
linkedin_username: josgiraldoruiz
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is José and I'm a software engineer.
   I could say that I am a javascript/node/backend/react/fullstack developer, but I find myself wanting to explore further in other software fields and excited to learn and grow within them. 
   Or at least, not all. I also have experience making software and web apps from scratch, I am good at listening to client ideas and making them a reality. 
   I have worked at a number of companies, in which I have gained experience and teamwork skills.

  I am most experienced in: <mark>MongoDB</mark> <mark>Express</mark> <mark>React</mark> <mark>Node</mark> 

  I have also worked with: <mark>React Native</mark> <mark>Angular 8</mark> <mark>Java</mark> <mark>Python</mark> <mark>PHP</mark> <mark>Laravel</mark> <mark>Docker</mark> <mark>Grahpql</mark> <mark>Next JS</mark> <mark>pm2</mark> <mark>nginx</mark>

  I am currently looking for giving a turn to my career. The fields I am most interested in are : <mark>Blockchain</mark> <mark>AI</mark> <mark>Cibersecurity</mark>    
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: La Mazadera
        link: lamazadera.es
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An ecommerce for the zoosanitary sector.
        description: | # this will include new lines to allow paragraphs
          This project was a job I developed as a freelance. I started this project from scratch, applying for a grant from the local government. In this application it was necessary to include the requirements, the deadlines, and the costs of the project.
          The grant was awarded, and I deployed the full ecommerce web application, using a graphql template, which was completed and adapted for the current necesities. 
      - layout: top-middle
        title: Boorpret
        link: boorpret.com
        quote: >
          Making ideas reality.
        description: | # this will include new lines to allow paragraphs
          In 2019 I co-founded Boorpret with some friends from university, a company that develops all kinds of applications, websites and graphic design projects. 
          We were on our own and we did it. To this day, they keep on makingt the web world a better place. 
          I will always remember how we created a company from zero and worked non-stop for over a year to lift it up.
          Within my responsibilities I had to talk to clients, manage a small team of developers, design and develop applications, 
          make the skeleton for the backend of all our applications, and so many other tasks I never saw myself doing before.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boorpret
        link: boorpret.com
        sub_title: Software engineering
        caption: September 2019 - December 2020
        quote: >
          Making ideas a reality.
        description: | # this will include new lines to allow paragraphs
            This has been for me the most important experience in my short career. I had a lot of responsibilities, from managing my own time as well as my teammates', 
            to writing contracts, down to dealing closely with our clients. I was here for only a year, but it was a really intense and fruitful experience.
      - layout: left
        title: Ayesa
        link: ayesa.com
        sub_title: Junior fullstack developer
        caption: April 2018 - March 2019
        quote: >
          First work and first contact with a relatively big company.
        description: | # this will include new lines to allow paragraphs
            In Ayesa I worked in a eight people team, in which I had a Junior position. 
            In this work we used <mark>Angular 8</mark> for the frontend and <mark>Java</mark> for the backend.
             Even though I was a junior developer, me and my teamworkers had a lot of autonomy and responsabilities, 
             and in some moments I found myself supervising code and teaching skills to my coworkers.
      - layout: left
        title: Prise
        link: prise.es
        sub_title: Internship
        caption: September 2017 - March 2018
        quote: >
          A great internship with fantastic professionals
        description: | # this will include new lines to allow paragraphs
            I started the internship making some automatic testing, 
            which was used for checking if some services were still working day after day. 
            After that, I developed an internal dashboard for measuring the use of the resources of the company.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Sevilla - ETSII
        caption: 2013 - 2019
        sub_title: Degree in Computer Software Engineering
        description: | # this will include new lines to allow paragraphs
          During my time at university I learnt a huge spectrum of skills, from writing a budget to deploying a web application.  
          
          I also expent a lot of my free time playing football with the college team, which I captained for two years, winning the city tournament twice. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Travelling

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
