# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: José Giraldo Ruiz
title: Software engineering
email: dragojola@gmail.com
website: josgirrui.github.io/josgirrui/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  josgirrui
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: josgiraldoruiz
linkedin_username: josgiraldoruiz
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's José and I'm a software engineering. I could say that I am a javascript/node/backend/react/fullstack developer, but that is not what I want to be. Or at least, not all. As well as the said before, I have experience making software and web apps from scratch, listening ideas and making them realities. I have worked at a number of companies, in which I have gained experience and teamwork.

  I am most skilled in: <mark>MongoDB</mark> <mark>Express</mark> <mark>React</mark> <mark>Node</mark> 

  I also have worked with: <mark>React Native</mark> <mark>Angular 8</mark> <mark>Java</mark> <mark>Python</mark> <mark>PHP</mark> <mark>Laravel</mark> <mark>Docker</mark> <mark>Grahpql</mark> <mark>Next JS</mark> <mark>pm2</mark> <mark>nginx</mark>

  I am currently looking for giving a turn to my career. The paths I am more interested in are : <mark>Blockchain</mark> <mark>AI</mark> <mark>Cibersecurity</mark>    
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: La Mazadera
        link: lamazadera.es
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An ecommerce for the zoosanitary sector.
        description: | # this will include new lines to allow paragraphs
          This project was a job made as a freelance. The project started applying for a grant to the local government. In this application it was necessary to include the requirements, the deadlines, and the costs of the project.
          The grant was awarded, and I deployed the full ecommerce web application, using a grahpql template, which was completed and adapted for the current necesities. 
      - layout: top-middle
        title: Boorpret
        link: boorpret.com
        quote: >
          Making ideas reality.
        description: | # this will include new lines to allow paragraphs
          During a year me and my partners create Boorpret, a company that developed all kinds of applications. We were on our own and we did it. They still making the world wide web a better place without me, and I will allways remembered how we create a company from zero.
          Within my responsabilities I had talk with clients, manage a small team, design and develope applications, make the skeleton for the backend of all our applications, and more that I can't even relate.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boorpret
        link: boorpret.com
        sub_title: Software engineering
        caption: September 2019 - December 2020
        quote: >
          Making ideas reality.
        description: | # this will include new lines to allow paragraphs
            This had been the most important experience in my short career. I had a lot of responsabilities, coming from managing my own time, at writing contracts.  I were here for only a year, but it was a really intense experience.
      - layout: left
        title: Ayesa
        link: ayesa.com
        sub_title: Junior fullstack developer
        caption: April 2018 - March 2019
        quote: >
          First work and first contact with a relatively big company.
        description: | # this will include new lines to allow paragraphs
            In Ayesa I work in a eight people team, in which I had a Junior position and responsabilities. In this work we used <mark>Angular 8</mark> for the frontend and <mark>Java</mark> for the backend. Even I was a junior developer, me and my teamworkers had a lot of autonomy and responsabilities, and in some moments I found myself supervising code and teaching skill to my coworkers.
      - layout: left
        title: Prise
        link: prise.es
        sub_title: Internship
        caption: September 2017 - March 2018
        quote: >
          Some incredible practices with fantastic professionals
        description: | # this will include new lines to allow paragraphs
            I started the internship making some automatic testing, which was used for testing if some services still working day after day. After that, I developed an internal dashboard for measure the use of the resources of the company.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Sevilla - ETSII
        caption: 2013 - 2019
        sub_title: Degree in Computer Software Engineering
        description: | # this will include new lines to allow paragraphs
          During my time at the university I learnt a huge spectrum of skills, from writing a budget to deploy a web application. I could have done better, but I was not enought focused and motivated at the moment. 
          
          I expend a lot of my free time playing football with the college team, which I captained for two years, winning the city tournament two times. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Traveling

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
